apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-income-expense-deployment
spec:
  replicas: 2
  selector:  # Add the selector field to match the template labels
    matchLabels:
      app: springboot-k8s-income-expense
  template:
    metadata:
      labels:
        app: springboot-k8s-income-expense
    spec:
      containers:
        - name: springboot-k8s-income-expense
          image: arivanan2001/income-expense
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-income-expense-svc
spec:
  selector:
    app: springboot-k8s-income-expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
