server:
  address: 0.0.0.0

  port: 8080  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker  # Last specified DB name
    username: postgres
    password: Bravin16@
    driver-class-name: org.postgresql.Driver  # Added from second config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Added from second config
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Added from second config

app:
  jwt:
    secret: secureSecretKeyForJwtSigningAndValidation5678901234567890
    expiration-ms: 86400000